version: '3'
services:
  http:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./local.conf:/etc/nginx/conf.d/default.conf
      - ./ca:/etc/ssl/ca
      - ./www:/var/www